version: "3.9"

services:
  # PostgreSQL Database
  db:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: salim_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks: [app-net]

  # FastAPI Application
  api:
    build: .
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      ENDPOINT_URL: "http://localstack:4566"
      REGION: "us-east-1"
      AWS_ACCESS_KEY: "test"
      AWS_SECRET_ACCESS_KEY: "test"
      BUCKET_NAME: "gov-price-files-hanif-2025"
      DYNAMODB_TABLE: "gov_price_data"
      QUEUE_URL: "https://sqs.us-east-1.localstack.localstack.cloud:4566/000000000000/price-data-queue"
      QUEUE_NAME: "price-data-queue"
      DLQ_QUEUE_NAME: "dlq-price-data-queue"
      NOMINATIM_CONTACT: "netanelnagar1234@gmail.com"
      NOMINATIM_URL: "https://nominatim.openstreetmap.org/search"
      DATABASE_URL: "postgresql+psycopg2://postgres:postgres@db:5432/salim_db"
      
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./:/app
    networks: [app-net]

  crawler:
    build:
      context: .
      dockerfile: crawler/Dockerfile.crawler
    environment:
      GOV_URL: "https://www.gov.il/he/pages/cpfta_prices_regulations"
      CRAWL_EVERY_MINUTES: "5"
      REGION: "us-east-1"
      AWS_ACCESS_KEY: "test"
      AWS_SECRET_ACCESS_KEY: "test"
      BUCKET_NAME: "gov-price-files-hanif-2025"
      ENDPOINT_URL: "http://localstack:4566"
    depends_on:
      db: { condition: service_healthy }
      localstack: { condition: service_healthy }
    networks: [app-net]

  extractor:
    build:
      context: .
      dockerfile: extractor/Dockerfile.extractor
    environment:
      EXTRACT_EVERY_MINUTES: "5"
      ENDPOINT_URL: "http://localstack:4566"
      REGION: "us-east-1"
      AWS_ACCESS_KEY: "test"
      AWS_SECRET_ACCESS_KEY: "test"
      BUCKET_NAME: "gov-price-files-hanif-2025"
      DYNAMODB_TABLE: "gov_price_data"
      QUEUE_URL: "https://sqs.us-east-1.localstack.localstack.cloud:4566/000000000000/price-data-queue"
      QUEUE_NAME: "price-data-queue"
      DLQ_QUEUE_NAME: "dlq-price-data-queue"
      NOMINATIM_CONTACT: "netanelnagar1234@gmail.com"
      NOMINATIM_URL: "https://nominatim.openstreetmap.org/search"
      DATABASE_URL: "postgresql+psycopg2://postgres:postgres@db:5432/salim_db"
    command:
       [
         "sh",
         "-lc",
         "echo 'extractor: waiting 45s…'; sleep 45; python -u /app/extractor/extractor.py",
       ]
    depends_on:
      db: { condition: service_healthy }
      localstack: { condition: service_healthy }
    networks: [app-net]

  enricher:
    build:
      context: .
      dockerfile: enricher/Dockerfile.enricher
    environment:
      ENRICH_EVERY_MINUTES: "5"
      ENDPOINT_URL: "http://localstack:4566"
      REGION: "us-east-1"
      AWS_ACCESS_KEY: "test"
      AWS_SECRET_ACCESS_KEY: "test"
      BUCKET_NAME: "gov-price-files-hanif-2025"
      DYNAMODB_TABLE: "gov_price_data"
      QUEUE_URL: "https://sqs.us-east-1.localstack.localstack.cloud:4566/000000000000/price-data-queue"
      QUEUE_NAME: "price-data-queue"
      DLQ_QUEUE_NAME: "dlq-price-data-queue"
      NOMINATIM_CONTACT: "netanelnagar1234@gmail.com"
      NOMINATIM_URL: "https://nominatim.openstreetmap.org/search"
      DATABASE_URL: "postgresql+psycopg2://postgres:postgres@db:5432/salim_db"
    command:
        [
         "sh",
         "-lc",
         "echo 'enricher: waiting 60s…'; sleep 60; python -u /app/enricher/enricher.py",
        ]
    depends_on:
      db: { condition: service_healthy }
      localstack: { condition: service_healthy }
    networks: [app-net]


  localstack:
    container_name: localstack
    image: localstack/localstack:latest
    ports:
      - "4566:4566"
    environment:
      - SERVICES=s3,sqs,dynamodb
      - DEBUG=1
      - PERSISTENCE=1
    volumes:
      - localstack-data:/var/lib/localstack
      - /var/run/docker.sock:/var/run/docker.sock
    entrypoint:
      - /bin/sh
      - -lc
      - |
        set -e
        for f in /etc/localstack/init/ready.d/*.sh; do
          [ -f "$$f" ] && sed -i 's/\r$$//' "$$f" && chmod +x "$$f";
        done
        exec docker-entrypoint.sh localstack
    healthcheck:
      test: ["CMD", "curl", "-sf", "http://localhost:4566/_localstack/health"]
      interval: 5s
      timeout: 3s
      retries: 20
    networks: [app-net]

volumes:
  postgres_data:
  localstack-data:
networks:
  app-net:
    driver: bridge