services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: salim_db
    ports: ["5432:5432"]
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build: .
    ports: ["8000:8000"]
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/salim_db
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./app:/app/app

  localstack:
    image: localstack/localstack:latest # שימוש בגרסה האחרונה
    ports:
      - "4566:4566"
      - "4510-4559:4510-4559"
    environment:
      - PERSISTENCE=1
      - SERVICES=s3,sqs,dynamodb,lambda
      - DEBUG=1
    volumes:
      - localstack_data:/var/lib/localstack
      - "/var/run/docker.sock:/var/run/docker.sock"

  consumer:
    build: .
    command: python -u consumer.py
    environment:
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_DEFAULT_REGION=us-east-1
      - AWS_ENDPOINT_URL=http://localstack:4566
      - QUEUE_NAME=prices-queue
      - DATABASE_URL=postgresql+psycopg2://postgres:postgres@db:5432/salim_db
      - DLQ_NAME=prices-queue-dlq
    depends_on:
      db:
        condition: service_healthy
      localstack:
        condition: service_started
    restart: on-failure

volumes:
  postgres_data:
  localstack_data: