name: salim
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: salim_db
    ports: ["5432:5432"]
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build: .
    ports: ["8000:8000"]
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/salim_db
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./app:/app/app
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/v1/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  localstack:
    image: localstack/localstack:4.7
    container_name: localstack-s3
    ports:
      - "4566:4566"
      - "4510-4559:4510-4559"
    environment:
      - SERVICES=s3,sqs,dynamodb,lambda,iam,logs
      - DEBUG=1
      - PERSISTENCE=1
      - LAMBDA_DOCKER_NETWORK=salim_default
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - localstack_data:/var/lib/localstack
      - ./localstack:/etc/localstack/init/ready.d/
      - /var/run/docker.sock:/var/run/docker.sock

    healthcheck:
      test: ["CMD", "bash", "-lc", "awslocal s3 ls >/dev/null 2>&1 || exit 1"]
      interval: 20s
      timeout: 10s
      retries: 5
      start_period: 25s

volumes:
  postgres_data:
  localstack_data:
