version: "3.9"

services:
  # PostgreSQL Database
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: salim_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app-net

  # LocalStack (S3 simulator)
  localstack:
    container_name: s3-simulator
    image: localstack/localstack:latest
    ports:
      - "4566:4566" # edge port
    environment:
      - SERVICES=s3
      - DEBUG=1
      - S3_SKIP_SIGNATURE_VALIDATION=1
      - PERSISTENCE=1
    volumes:
      - localstack-data:/var/lib/localstack
      - /var/run/docker.sock:/var/run/docker.sock
      - ./gov_crawler/scripts/init-s3.sh:/etc/localstack/init/ready.d/init-s3.sh
    healthcheck:
      test: ["CMD", "curl", "-sf", "http://localhost:4566/_localstack/health"]
      interval: 5s
      timeout: 3s
      retries: 20
    networks:
      - app-net

  # FastAPI Application
  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      # DB
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/salim_db

      # S3/LocalStack
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_REGION=us-east-1
      - S3_ENDPOINT_URL=http://localstack:4566
      - S3_BUCKET=supermarkets
    depends_on:
      db:
        condition: service_healthy
      localstack:
        condition: service_healthy
    volumes:
      - ./app:/app/app
    healthcheck:
      test: ["CMD", "curl", "-sf", "http://localhost:8000/api/v1/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - app-net

  crawler:
    build:
      context: .
      dockerfile: gov_crawler/Dockerfile.crawler
    environment:
      CRAWL_EVERY_MINUTES: "60"
      AWS_ACCESS_KEY_ID: test
      AWS_SECRET_ACCESS_KEY: test
      AWS_REGION: us-east-1
      S3_ENDPOINT_URL: http://localstack:4566
      S3_BUCKET: supermarkets
      USE_CHROMIUM: "1"
      CHROME_BIN: /usr/bin/chromium
      TZ: Asia/Jerusalem
      LOCAL_DATA_DIR: "supermarkets"
      CONFIG_KEY: "supermarkets"

    depends_on:
      db:
        condition: service_healthy
      localstack:
        condition: service_healthy
    networks:
      - app-net

networks:
  app-net:
    driver: bridge

volumes:
  postgres_data:
  localstack-data:
