services:
  localstack:
    container_name: sqs-simulator
    image: localstack/localstack:latest
    ports:
      - "4567:4566"
    environment:
      - SERVICES=sqs
      - DEBUG=1
      - SQS_SKIP_SIGNATURE_VALIDATION=1
    volumes:
      - "localstack-data:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./init-sqs.sh:/etc/localstack/init/ready.d/init-sqs.sh"
    networks:
      - sqs-network

networks:
  sqs-network:
    driver: bridge

volumes:
  localstack-data: