services:
  localstack:
    container_name: s3-simulator


  lambda-function:
    build: ./lambda
    container_name: s3-lambda
    ports:
      - "8080:8080"
    environment:
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_DEFAULT_REGION=us-east-1
      - S3_ENDPOINT=http://localstack:4566
      - LAMBDA_PORT=8080
      - S3_BUCKET=test-bucket
    depends_on:
      - localstack
    networks:
      - s3-network
    command: python handler.py

  frontend:
    build: ./frontend
    container_name: s3-frontend
    ports:
      - "3000:3000"
    volumes:
      - "./frontend/src:/app/src"
      - "./frontend/public:/app/public"
    depends_on:
      - lambda-function
    networks:
      - s3-network

networks:
  s3-network:
    driver: bridge

volumes:
  localstack-data: