FROM python:3.11-slim


WORKDIR /app

COPY extractor/requirements.txt extractor/requirements.txt
RUN pip install --no-cache-dir -r extractor/requirements.txt

COPY extractor/ extractor/

WORKDIR /app/extractor
CMD ["python", "-u", " extractor.py"]