FROM python:3.11-slim


WORKDIR /app

COPY enricher/requirements.txt enricher/requirements.txt
RUN pip install --no-cache-dir -r enricher/requirements.txt

COPY enricher/ enricher/

WORKDIR /app/enricher
CMD ["python", "-u", "enricher.py"]