version: "3.8"

services:
  fastapi:
    container_name: rag-fastapi
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app  # Mount local code into container
    command: >
      uvicorn app:app --host 0.0.0.0 --port 8000 --reload
    environment:
      - PYTHONUNBUFFERED=1
